name: Windows Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:  
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Install boost
        id: install-boost
        uses: MarkusJx/install-boost@v2.1.0
        with:
          boost_version: 1.77.0
          platform_version: 2019

      - name: Make VS Project
        working-directory: libtrellis
        run: cmake -DBOOST_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }} .

      - name: Build
        working-directory: libtrellis
        run: msbuild libtrellis.sln

      - uses: actions/upload-artifact@v2
        name: Upload Release
        with:
          name: x
          path: ./

